#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		if [ "$remote_sha" = $z40 ]
		then
			# New branch, examine all commits
			range="$local_sha"
		else
			# Update to existing branch, examine new commits
			range="$remote_sha..$local_sha"
		fi

		# Check for WIP commit
		commit=`git rev-list -n 1 --grep '^WIP' "$range"`
		if [ -n "$commit" ]
		then
			echo >&2 "Found WIP commit in $local_ref, not pushing"
			exit 1
		fi
	fi
done

echo >&2 "Running Necronomicon tests"

# check windows build path first, then linux build path. this all needs some more general solution, but just getting things working for now
NECRO_EXE=./build/Debug/necro.exe
if test -f "$NECRO_EXE"; then
    ./build/Debug/necro.exe -test all 2>&1
else
    valgrind --error-exitcode=255 --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all --track-origins=yes --verbose --log-file=.valgrind/valgrind-out.txt ./result/build/necro -test all 2>&1
fi

result=$?
if [ $result -eq 0 ]
then
  echo "Necronomicon tests completed succesfully"
elif [ $result -eq 2 ]
then
  echo "Necronomicon test could not open sub-process"
else
  echo "Necronomicon tests failed. git push aborted." >&2
  echo $result
  exit 1
fi

exit 0
